---
- name: Install Web Server
  hosts: all
  become: yes
  gather_facts: true
  pre_tasks:
  - name: Stop nginx service
    service:
      name: nginx
      state: stopped
      enabled: no
  # - name: Stop apache2 service
  #   service:
  #     name: apache2
  #     state: stopped
  #     enabled: no
  roles:
    - install-apache
    # - install-nginx
...
