---
- hosts: all
  gather_facts: false
  vars:
    - file_name: 00-good-day
    - file_path: /etc/update-motd.d/{{ file_name }}
    - welcome_text: "#!/bin/sh\necho \"*** Have a nice day! ***\""
  tasks:
  - name: Create new motd element
    become: yes
    file:
      path: "{{ file_path }}"
      mode: 0755
      state: touch
  - name: Edit new motd
    lineinfile:
      path: "{{ file_path }}"
      line: "{{ welcome_text }}"
...
